### ISSUE TITLE
请问spricoder博客是否接受pr

### ISSUE THREAD

**Issue by CybCom** [stormbroken/stormbroken.github.io#5]
首先感谢学长的博客，您的分享帮助了无数后来者的学习生活。
不过最近偶有发现问题，希望能予更正，请问该博客是否接受pr？

**Comment by SpriCoder** [comment]
本仓库是接受Pr的，非常欢迎提交，但是由于框架是hexo，所以我会在md源文件对应位置修改后进行提交，届时会在每个Pr标记修改的commitId

**Comment by CybCom** [comment]
好的，我提交时没注意找到正确的源文件。再次感谢您的博客创作。
